Class {
	#name : #'BaselineOfTrabajo_Final_POO',
	#superclass : #Object,
	#category : #'BaselineOfTrabajo_Final_POO'
}

{ #category : #'as yet unclassified' }
BaselineOfTrabajo_Final_POO >> baselina: spec [
<baseline>
spec for:#common
do:[
	"the main code of the baseline will go here"
	spec
		package:'Trabajo_Final_POO'.

	]
]

{ #category : #ConfigurationOfFoo }
BaselineOfTrabajo_Final_POO >> projectClassMethodSource [ 
^MetacelloCypressBaselineProject.
]
